### PR TITLE
feat: added listener guide

### PR DESCRIPTION
**Pull request by UndiedGamer**
**Please describe the changes this PR makes and why it should be merged:**
Added listener guide and tested

### CODE REVIEW

**Comment by UndiedGamer** [comment]
@kyranet please review this

**Comment by UndiedGamer** [comment]
@kyranet i have fixes the deps, pls review

**Comment by UndiedGamer** [comment]
> @kyranet i have fixes the deps, pls review

fixed*

**Comment by kyranet** [comment]
I'm not a fan of the code, doesn't go enough in-depth, and there were still unwanted changes in two files.

I just pushed ebe3859fa814faf74022d299334b7e3431b78599 with a full guide on listeners, including advanced options.

**Pull request closed without merging**
